### ISSUE TITLE
Update User model

### ISSUE THREAD

**Issue by PaoloGaudiel** [dev-mission/fellowship2023-alumni#9]

**Comment by PaoloGaudiel** [comment]
Sequelize migration generate
Query interface add column function

async up and down should be opposite (the former adds and the latter removes)

make sure the tests pass

**Comment by PaoloGaudiel** [comment]
toJSON() Function in models/user.js - Does that need to be updated?

**Comment by francisli** [comment]
Yes, if you want any new attributes in the User model to be included when it is converted to JSON for sending in an HTTP response, you'll want to edit toJSON() as well...
